
name: sinopia
version: 0.2.0
description: Private npm repository server

author:
  name: Alex Kocharin
  email: alex@kocharin.ru
 
repository:
  type: git
  url: https://github.com/rlidwka/sinopia

main: index.js

bin:
  sinopia: ./bin/sinopia

dependencies:
  express: '>= 3.2.5'
  commander: '>= 1.1.1'
  js-yaml: '>= 2.0.5'
  cookies: '>= 0.3.6'
  request: '*'
  async: '*'
  semver: '*'
  minimatch: '*'
  through: '*'

keywords: # TODO
  - private
  - repository
  - registry

preferGlobal: true
license: BSD

