# use "yapm install ." if you're installing this from git repository

name: sinopia
version: 0.5.9
description: Private npm repository server

author:
  name: Alex Kocharin
  email: alex@kocharin.ru
 
repository:
  type: git
  url: git://github.com/rlidwka/sinopia

main: index.js

bin:
  sinopia: ./bin/sinopia

dependencies:
  express: '>= 3.2.5'
  commander: '>= 1.1.1'
  js-yaml: '>= 2.0.5'
  cookies: '>= 0.3.6'
  request: '*'
  async: '*'
  semver: '>= 2.0.5' # compareLoose
  minimatch: '*'
  bunyan: '>= 0.16.4'
  fs-ext: '*'

devDependencies:
  rimraf: '*'
  mocha: '*'

  # linting tools
  eslint: '*'
  #eslint-stylish: '*'

keywords:
  - private
  - package
  - repository
  - registry
  - modules
  - proxy
  - server

scripts:
  test: mocha ./test/functional ./test/unit
  lint: eslint -c ./.eslint.js ./lib

# we depend on streams2 stuff
# it can be replaced with isaacs/readable-stream, ask if you need to use 0.8
engines:
  node: '>=0.10'

preferGlobal: true

# http://www.wtfpl.net/txt/copying/
license: WTFPL

