
name: npmrepod
version: 0.0.1
description: Private npm repository server

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

main: index.js

bin:
  npmrepod: ./bin/npmrepod
  
dependencies:
  express: '*'
  commander: '*'
  
preferGlobal: true
license: BSD

