
name: npmrepod
version: 0.0.1
description: Private npm repository server

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

main: index.js

bin:
  npmrepod: ./bin/npmrepod

dependencies:
  express: '>= 3.2.5'
  commander: '>= 1.1.1'
  js-yaml: '>= 2.0.5'
  cookies: '>= 0.3.6'

preferGlobal: true
license: BSD

